#pragma config(Sensor, in1,    Right,          sensorPotentiometer)
#pragma config(Sensor, in2,    Left,           sensorPotentiometer)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           backLeftArm,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port7,           backRightArm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           frontLeftArm,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRightArm, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//2200
//800
int chnl1 = 0, chnl3 = 0, threshold = 10;
int fullPower = 127;
int integral = 0;
int leftBal = Left;
int rightBal = Right;
int leftSense = Left;
int rightSense = Right;
task main()
{
	leftSense = Left-leftBal;
	rightSense = Right - rightBal;
	while(true) {
		if(abs(vexRT[Ch1]) > threshold) {
			chnl1 = vexRT[Ch1];
		}
		else {
			chnl1 = 0;
		}
		//Create deadzone for Channel 3
		if(abs(vexRT[Ch3]) > threshold) {
			chnl3 = vexRT[Ch3];
		}
		else {
			chnl3 = 0;
		}
		//driverDeadzone();

		//Joystick control for driver
		motor[frontRight] = chnl3-chnl1;
		motor[backRight] = chnl3-chnl1;
		motor[backLeft] = chnl3+chnl1;
		motor[frontLeft] = chnl3+chnl1;
		string dir;
		if(vexRT[Btn5D] == 1) {
			dir = "down";
			checkEven(leftSense, rightSense, dir);
			//down
		}
		else if(vexRT[Btn6D] == 1) {
			dir = "up";
			checkEven(leftSense, rightSense, dir);
			//up
		}
		else {
			dir = "balance";
			checkEven(leftSense, rightSense, dir);
			//stop
		}
	}
}

int proportion(int bigger, int smaller, string mode){//returns slowdown for side further ahead
	int error = (bigger - smaller)/1400;
	integral += (time1[T1]/1000)*(error);//time1 = every 1000th of a second (1 ms)
	int value = 127*(error + integral);


	if(mode=="move"){
		if(value > 127){
			return 127;
		}else{
			return value;
		}
	}//return from 0-127 to subtract from motor power, full to 0 power
	else if(mode=="balance"){
		if(value > 254){
			return 254;
		}else{
			return value;
		}
	}//return from 0-254 to subtract from motor power full power forward to full power backwards
	return 0;
}


void checkEven(int left, int right, string mode){
	string move = "move";
	if(left > right - 50&&left < right +50){//check if even
		clearTimer(T1);
		integral = 0;
		if(mode == "up"){//if moving up
			motor[backRightArm] = fullPower;
			motor[backLeftArm] = fullPower;
			motor[frontLeftArm] = fullPower;
			motor[frontRightArm] = fullPower;
		}else if(mode == "down"){//move down
			motor[backRightArm] = -fullPower;
			motor[backLeftArm] = -fullPower;
			motor[frontLeftArm] = -fullPower;
			motor[frontRightArm] = -fullPower;


		}else if(left > right){
			if(mode == "up"){//if moving up
			motor[backRightArm] = fullPower;
			motor[backLeftArm] = fullPower - proportion(leftSense, rightSense, move);
			motor[frontLeftArm] = fullPower - proportion(leftSense, rightSense, move);
			motor[frontRightArm] = fullPower;
		}else if(mode == "down"){//move down
			motor[backRightArm] = -fullPower + proportion(leftSense, rightSense, move);
			motor[backLeftArm] = -fullPower;
			motor[frontLeftArm] = -fullPower;
			motor[frontRightArm] = -fullPower + proportion(leftSense, rightSense, move);
		}else if(mode == "balance"){

			motor[backRightArm] = -fullPower + proportion(leftSense, rightSense, mode);
			motor[backLeftArm] = fullPower - proportion(leftSense, rightSense, mode);
			motor[frontLeftArm] = fullPower - proportion(leftSense, rightSense, mode);
			motor[frontRightArm] = -fullPower + proportion(leftSense, rightSense, mode);
		}


		}else if(right < left){
			if(mode == "up"){//if moving up
			motor[backRightArm] = fullPower;
			motor[backLeftArm] = fullPower - proportion(leftSense, rightSense, move);
			motor[frontLeftArm] = fullPower - proportion(leftSense, rightSense, move);
			motor[frontRightArm] = fullPower;
		}else if(mode == "down"){//move down
			motor[backRightArm] = -fullPower + proportion(leftSense, rightSense, move);
			motor[backLeftArm] = -fullPower;
			motor[frontLeftArm] = -fullPower;
			motor[frontRightArm] = -fullPower + proportion(leftSense, rightSense, move);
		}else if(mode == "balance"){

			motor[backRightArm] = -fullPower + proportion(leftSense, rightSense, mode);
			motor[backLeftArm] = fullPower - proportion(leftSense, rightSense, mode);
			motor[frontLeftArm] = fullPower - proportion(leftSense, rightSense, mode);
			motor[frontRightArm] = -fullPower + proportion(leftSense, rightSense, mode);
		}
		}
	}
}
