#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in2,    potArm1,        sensorPotentiometer)
#pragma config(Sensor, in3,    potArm2,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeMotor,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           topRightArm,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           bottomRightArm, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           topLeftArm,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           bottomLeftArm, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port7,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string beltDirection; //forward backward stop
string wheelRotation; // left right stop
string moveDirection; //forward backward left right stop
string armDirection; //moves arm up or down





void armtasks()
{
	if(armDirection == "up")
	{
		motor[port2] = -127;
		motor[port3] = -127;
		motor[port4] = -127;
		motor[port5] = -127;

	}
	if(armDirection == "down")
	{
		motor[port2] =  100;
		motor[port3] =  100;
		motor[port4] =  100;
		motor[port5] =  100;

	}


	if(armDirection == "stop")
	{
		motor[port2] = 0;
		motor[port3] = 0;
		motor[port4] = 0;
		motor[port5] = 0;

	}

}





void intake()
{
	if(beltDirection == "forward")
	{
		motor[port1] = -100;

	}

	if(beltDirection == "backward")
	{
		motor[port1] = 100;

	}
	if(beltDirection == "stop")
	{
		motor[port1] = 0;

	}

}



void movement() //forwards, backwards, left and right (strafing)
{


	if(moveDirection == "forward")
	{
		motor[port6] = 100;
		motor[port7] = 100;
		motor[port8] = 100;
		motor[port9] = 100;

	}

	if(moveDirection == "backward")
	{
		motor[port6] = -100;
		motor[port7] = -100;
		motor[port8] = -100;
		motor[port9] = -100;
	}

	if(moveDirection == "left")
	{
		motor[port6] = 100;
		motor[port7] = -100;
		motor[port8] = 100;
		motor[port9] = -100;
	}

	if(moveDirection == "right")
	{
		motor[port6] = -100;
		motor[port7] = 100;
		motor[port8] = -100;
		motor[port9] = 100;
	}

	if(moveDirection == "stop")
	{
		motor[port6] = 0;
		motor[port7] = 0;
		motor[port8] = 0;
		motor[port9] = 0;
	}




}

void rotation()
{


	if(wheelRotation == "left")
	{


		motor[port6] = 100;
		motor[port7] = 100;
		motor[port8] = -100;
		motor[port9] = -100;

	}

	if(wheelRotation == "right")
	{
		motor[port6] = -100;
		motor[port7] = -100;
		motor[port8] =  100;
		motor[port9] =  100;
	}
	if(wheelRotation == "stop")
	{
		motor[port6] =  0;
		motor[port7] =  0;
		motor[port8] =  0;
		motor[port9] =  0;

	}


}




task main()
{


	nMotorEncoder[port6] = 0;
	moveDirection = "forward"; //sets diretion of movement() to go forward

	while(nMotorEncoder[port6] < 400 && moveDirection == "forward")// go forward till encoder < 450
	{
	movement();
	}

	moveDirection = "stop"; //sets movement() to stop

	movement();

	beltDirection = "backward"; //sets intake motor to go backwards

	if(beltDirection == "backward") //pick up starting cube
	{
	intake();
	wait1Msec(1700);

	}

	beltDirection = "stop"; // stop the belt
	intake();



	nMotorEncoder[port6] = 0;
	nMotorEncoder[port7] = 0;
	nMotorEncoder[port8] = 0;
	nMotorEncoder[port9] = 0;

	wheelRotation = "right"; //sets rotation to go right


	while(nMotorEncoder[port9] < 1300) //rotates right till motor encoder reaches
	{
	rotation();
	}

	wheelRotation = "stop";
	if(nMotorEncoder[port9] >= 1300) // stop the rotation

	{

	rotation();

	}

	nMotorEncoder[port6] = 0;
	moveDirection = "forward"; //sets diretion of movement() to go forward

	while(nMotorEncoder[port6] < 300 && moveDirection == "forward")// go forward till encoder < 450
	{
	movement();
	}

	moveDirection = "stop"; //sets movement() to stop

	movement();








	armDirection = "up"; // sets arm to go up
	while(SensorValue[potArm1] <= 2900 && SensorValue[potArm2] <= 1700) //values of lowest post
	{
		armtasks();
	}

	armDirection = "stop";


	armtasks();



	wait1Msec(300);

		nMotorEncoder[port6] = 0;
	moveDirection = "forward"; //sets diretion of movement() to go forward

	while(nMotorEncoder[port6] < 200 && moveDirection == "forward")// go forward till encoder < 100
	{
		movement();
	}

	moveDirection = "stop"; //sets movement() to stop

	movement();






	beltDirection = "forward";

	if(beltDirection == "forward") //pick up starting cube
	{
		intake();
		wait1Msec(4000);

	}

	beltDirection = "stop"; // stop the belt
	intake();

	wait1Msec(300);



	armDirection = "down"; // sets arm to go down

	while(SensorValue[potArm1] >= 2900 && SensorValue[potArm2] >= 1700) //values of lowest post
	{
		armtasks();
	}

	armDirection = "stop";

	armtasks();

	nMotorEncoder[port6] = 0;
	moveDirection = "backward"; //sets diretion of movement() to go backward

	while(nMotorEncoder[port6] > -350 && moveDirection == "backward")// go forward till encoder < 100
	{
		movement();
	}

	moveDirection = "stop"; //sets movement() to stop

	movement();

}
